#include "cprocessing.h"

CP_Sound sword_swing;
CP_Sound projectile_shoot;
CP_Sound pickUp;
CP_Sound nextlvl_sound;
CP_Sound buttonClickSound;
CP_Sound damageTaken;
CP_Sound gameOverSound;
CP_Sound backgroundMusic;
CP_Sound credits;
CP_Sound bossTime;
float backgroundVolume;
float sfxVolume;
int startCount;
float nextState;
int exitState;
int menuState;
int creditState;
int gameOverState;
int level2State;
int level3State;
int level4State;
float startCountG;
int playVictorySound;
float victorySoundCount;